mysite/urls.py
# -*- coding: utf-8 -*-
from django.contrib import admin
from django.urls import path, include # 追記7
import debug_toolbar
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')), # 追記6
]

if settings.DEBUG:
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

shop/urls.py
# -*- coding: utf-8 -*-
# 以下追記8
from django.urls import path
from . import views

# 追記
app_name = 'shop'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

shop/models.py
# -*- coding: utf-8 -*-
# 以下追記10→次はforms定義
from django.db import models

class Good(models.Model):
    # 商品テーブル

    class Meta:
        db_table = 'good'

    title = models.CharField(verbose_name='商品名' ,max_length=255)
    price = models.IntegerField(verbose_name='値段', null = True, blank=True)

    def __str__(self):
        return self.title

shop/forms.py
# -*- coding: utf-8 -*-
from django import forms


class GoodSearchForm(forms.Form):

    title = forms.CharField(
            initial = '',
            label = '商品名',
            required = False,
        )

    price = forms.IntegerField(
            initial = '',
            label = '値段',
            required = False,
        )

shop/views.py
# -*- coding: utf-8 -*-
# 以下追記9→次はmodels編集
from django.views import generic

from .models import Good
from .forms import GoodSearchForm
from django.db.models import Q


class IndexView(generic.ListView):

    paginate_by = 5
    template_name = 'shop/index.html'
    model = Good


    def post(self, request, *args, **kwargs):

        form_value = [
                self.request.POST.get('title', None),
                self.request.POST.get('price', None),
            ]


        request.session['form_value'] = form_value

        # 不明
        self.request.GET = self.request.GET.copy()
        self.request.GET.clear()

        # generic/list.pyのget()メソッドが呼び出される
        return self.get(request, *args, **kwargs)


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        title = ''
        price = ''

        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            title = form_value[0]
            price = form_value[1]

        #import pdb; pdb.set_trace()
        default_data = {'title' : title, 'price' : price}

        # やや不明（どうやってディクショナリのkeyをフォームのtitle, priceに振り分けているのか）
        test_form = GoodSearchForm(initial = default_data)

        context['test_form'] = test_form
        return context


    def get_queryset(self): # 呼び出された（オーバーライドされたメソッド）

        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            title = form_value[0]
            price = form_value[1]

            condition_title = Q()
            condition_price = Q()

            if len(title) != 0 and title[0]:
                condition_title = Q(title__contains = title)
            if len(price) != 0 and price[0]:
                condition_price = Q(price__contains = price)

            return Good.objects.select_related().filter(condition_title & condition_price)

        else:
            return Good.objects.none()

shop/templates/shop/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- bootstrap4 -->
        {% load bootstrap4 %}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
        <!-- bootstrap4 -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <script type="text/javascript">
            $(function() {
                var topBtn = $('#page-top');
                topBtn.hide();
                //スクロールが500に達したらボタン表示
                $(window).scroll(function () {
                    if ($(this).scrollTop() > 500) {
                        topBtn.fadeIn();
                    } else {
                        topBtn.fadeOut();
                    }
                });
                //スクロールしてトップ
                topBtn.click(function () {
                    $('body,html').animate({
                        scrollTop: 0
                    }, 500);
                    return false;
                });
            });
        </script>
        <title>{% block title %}Search{% endblock %}</title>
    </head>
    <body>
        <!-- ナビゲーションバーの設定 -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
            <div class="container">
            	<!-- URL設定の修正に注意する→indexの存在場所 -->
                <a class="navbar-brand" href="{% url 'shop:index' %}">Search</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
							<!-- URL設定の修正に注意する→indexの存在場所 -->
                            <a class="nav-link" href="{% url 'shop:index' %}">TOP</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">ログアウト</a>
                        </li>
                    {% else %}
                        {% url 'login' as login %}
                        {% ifnotequal request.path login %}
                            <li class="nav-item">
                                <a class="nav-link" href="" class="login">ログイン</a>
                            </li>
                        {% endifnotequal %}
                    {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
         <main>
            {% block content %}
            {% endblock %}
        </main>
        <p id="page-top"><a href="#">PAGE TOP</a></p>
            <footer class="py-4 bg-dark">
                <div class="container text-center">
                    <p class="text-light"><small>Copyright &copy;2019 Search, All Rights Reserved.</small></p>
                </div>
            </footer>
    </body>
</html>

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% block content %}
<div class="col-lg-6 offset-lg-3">
     <h1>検索条件</h1>
    <form method="POST">
        {% csrf_token %}
        <!-- test_formに格納した「検索タイトル」・「価格」を順に取り出して表示 -->
        {% for field in test_form %}
            <div class="form-group form-inline">
                <label class="col-md-offset-2 col-md-3 control-label">{{ field.label }}:</label>
                <div class="col-md-8">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        <input class="btn btn-success offset-md-8 col-md-3" type="submit" id="button" name="button" value="検索">
    </form>
    <h1>検索結果</h1>
    <section class="post-list">
        {% if object_list|length == 0 %}
            <p>検索結果が存在しません。</p>
        {% else %}
            <table class="table table-hover table-bordered">
                <tr>
                    <th>タイトル</th>
                    <th>価格</th>
                </tr>
                <tbody>
                {% for post in object_list %}
                    <tr>
                        <td width="35%">{{ post.title }}</td>
                        <td width="65%">{{ post.price }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </section>
    <div class="col-6 offset-3 justify-content-center">
        {% if is_paginated %}
            {% include 'pagination.html' %}
        {% endif %}
    </div>
</div>
{% endblock %}

shop/templates/shop/logged_out.html
<!-- 今回は未使用→ログイン機能実装時に使用 -->
<!-- base.htmlのテンプレート引用 -->>
{% extends 'base.html' %}

<!-- タイトル部分をテンプレートから変更 -->>
{% block title %}Logout{% endblock %}

<!-- コンテンツ部分をテンプレートから変更 -->>
{% block content %}
    <div class="col-md-6 offset-md-3">
        <h1>ログアウトしました。</h1>
        <p>ご利用ありがとうございました。</p>
    </div>
    <hr>
    <section>
        <div class="col-md-6 offset-md-3">
            <button type="submit" class="btn btn-primary col-md-4" onClick="location.href='{% url 'search:index' %}'">再度ログイン</button>
        </div>
    </section>
{% endblock %}

shop/templates/shop/login.html
<!-- 今回は未使用→ログイン機能実装時に使用 -->
<!-- templates/registration/login.html -->
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <h1>ログイン</h1>
    <section class="common-form">
        {% if form.errors %}
        <p class="error-msg">ユーザー名とパスワードが一致しません。再試行してください。</p>
        {% endif %}

        {% if next %}
        {% if user.is_authenticated %}
        <p class="info-msg">Your account doesn't have access to this page. To proceed,
            please login with an account that has access.</p>
        {% else %}
            {% if not form.errors %}
        <p class="info-msg">ログインしてください。</p>
            {% endif %}
        {% endif %}
        {% endif %}

        <form method="post" action="{% url 'login' %}">

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="submit">ログイン</button>
                <input type="hidden" name="next" value="{{ next }}"/>
        </form>
    </section>
</div>
{% endblock %}

shop/templates/shop/pagination.html
<nav aria-label="ページ送り">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ i }} <span class="sr-only">(現位置)</span></a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
        {% endif %}
    </ul>
</nav>